### PR TITLE
Remove deprecated Socks5 library

### PR DESCRIPTION
**Pull request by boergegrunicke**
From the issues on GitHub, it even looks like the combination of the telegram bot API and the socks5 library could be broken at all, so I would just completely delete it (I assume nobody is using this proxy functionality).

Fixes: #689

### CODE REVIEW

**Comment by mcm1957** [comment]
@boergegrunicke
Thanks for spe nding your time and providing this PR.

I'm not sure wether simply removing a functionality is appropiate. Will discuss with core team.

Anyway:
Why do you commit admin changes? I do not see a change in corresponding source code?
On the other side if socks proxy is removed, the GUI must be adapted too to remove the option at admin UI.
But please do not spend time on ui programming as long as we did not decide wether sock5 to remove or not.

**Comment by Apollon77** [comment]
I can only imagine that proxy support is for users in countries where telegram is officially blocked (like china or such). For me ok to remove and we see feedback. but please with a makjor version increase and clean "Breaking" info in changelog

**Comment by mcm1957** [comment]
@boergegrunicke 
First feedbackfrom core team seems to confirm your suggestion and socksv5 will likely be removed.

I would like to  ask you

- [ ] to remove the admin commits from the PR ( I assume you did not change anything at custom component, so its not required to commit any changes)
- [ ] to remove socksv5 option from jsonConfig.json (as it is obsolete now)

Thanks in advance

**Comment by boergegrunicke** [comment]
@mcm1957
The option in the settings is removed and regarding the admin, your assumption is correct. This happened all automatically, I will check if it is running with just reverting, later.

**Comment by boergegrunicke** [comment]
@mcm1957 I removed the admin file changes now. As soon as I run it, the files are automatically changed again, but all this is not included in the pr now.

**Comment by mcm1957** [comment]
Thanks.
Yes build recreates the files. But if no changes to source are done I think its more secure to not comit them.

I ll check / merge during weekend

THANJS FOR YOUR SUPPORT

**Pull request merged**
